/**
 * Instrument Calm stamps, ported pixel for pixel from the kit
 * (~/Desktop/Instrument-Calm-Design-Language, stamps v2.1, stamps/stamps.json and
 * tools/stamps.py). Reference library entry 008.
 *
 * A stamp is a readable icon made from real storage objects, in hard pixel
 * blocks on a 16-cell grid: "#" is ink, "@" is the one accent group (the verb),
 * "." is ground. The bitmaps are the source of truth; do not edit them by hand
 * here. Three stamps were added on 2026-10-07 for portal kinds the kit set does
 * not cover (links, posts, reviews), drawn to the kit's grammar and checked at
 * 16, 24, 32 and 64px. Fold them back into the kit's tools/stamps.py.
 */

export type StampKey =
  | "console"
  | "facility"
  | "occupancy"
  | "tenants"
  | "leads"
  | "move-ins"
  | "reserve"
  | "proven-ads"
  | "recreate"
  | "ad-studio"
  | "campaigns"
  | "landing-page"
  | "reports"
  | "market"
  | "pricing"
  | "revenue"
  | "diagnostic"
  | "tools"
  | "access"
  | "security"
  | "upload"
  | "onboarding"
  | "calls"
  | "messages"
  | "settings"
  | "help"
  | "links"
  | "posts"
  | "reviews";

export interface StampDef {
  key: StampKey;
  label: string;
  meaning: string;
  objects: string;
  uses: string;
  group: string;
  bitmap: string[];
}

export const STAMPS: Record<StampKey, StampDef> = {
  "console": {
    key: "console",
    label: "Console",
    meaning: "Everything at a glance: a gauge set in the facility wall",
    objects: "storage building front + instrument gauge with one needle",
    uses: "/admin/console, portal Dashboard, Studio home",
    group: "Shell",
    bitmap: [
      "................",
      "################",
      "################",
      ".##..........##.",
      ".##...####...##.",
      ".##..##..##..##.",
      ".##.##....@@.##.",
      ".##.#....@@#.##.",
      ".##.#...@@.#.##.",
      ".##.#..@@..#.##.",
      ".##.#..@@..#.##.",
      ".##..........##.",
      ".##..........##.",
      ".##..........##.",
      "################",
      "................",
    ],
  },
  "facility": {
    key: "facility",
    label: "Facility",
    meaning: "One facility: a storage building with roll-up doors",
    objects: "flat-roof building + two ribbed roll-up doors + ground line",
    uses: "Facility Manager, Facilities, facility chip, Portfolio",
    group: "Shell",
    bitmap: [
      "................",
      "................",
      "................",
      "################",
      "################",
      "#..............#",
      "#..............#",
      "#.@@@@@..#####.#",
      "#.@@@@@..#####.#",
      "#..............#",
      "#.@@@@@..#####.#",
      "#.@@@@@..#####.#",
      "#..............#",
      "#.@@@@@..#####.#",
      "################",
      "................",
    ],
  },
  "occupancy": {
    key: "occupancy",
    label: "Occupancy",
    meaning: "How full the facility is: rented doors are solid",
    objects: "roof slab + three bays: two doors shut solid (rented), one open (vacant); doubles as a bar reading",
    uses: "Occupancy intel, occupancy tiles, reports",
    group: "Shell",
    bitmap: [
      "................",
      "................",
      "................",
      "################",
      "################",
      "................",
      ".####.####.#..#.",
      ".####.####.#..#.",
      ".####.####.#..#.",
      ".####.####.#..#.",
      ".####.####.#..#.",
      ".####.####.#..#.",
      ".####.####.#..#.",
      ".####.####.#..#.",
      "################",
      "................",
    ],
  },
  "tenants": {
    key: "tenants",
    label: "Tenants",
    meaning: "The people renting: a person in a unit doorway",
    objects: "roll-up door frame + tenant figure",
    uses: "Tenant CRM, renters, consumer side",
    group: "Shell",
    bitmap: [
      "................",
      ".##############.",
      ".##############.",
      ".##..........##.",
      ".##....@@....##.",
      ".##...@@@@...##.",
      ".##...@@@@...##.",
      ".##...@@@@...##.",
      ".##....@@....##.",
      ".##..........##.",
      ".##..######..##.",
      ".##.########.##.",
      ".##.########.##.",
      ".##.########.##.",
      ".##.########.##.",
      "................",
    ],
  },
  "leads": {
    key: "leads",
    label: "Leads",
    meaning: "A renter coming in: an arrow under a half-raised door",
    objects: "roll-up door frame + half-raised curtain + incoming arrow",
    uses: "Pipeline, Consumer Leads, Recovery, lead counts",
    group: "Leads",
    bitmap: [
      "................",
      ".##############.",
      ".##############.",
      ".##..........##.",
      ".##############.",
      ".##############.",
      ".##..........##.",
      ".##....@@....##.",
      ".##....@@....##.",
      ".##....@@....##.",
      ".##..@@@@@@..##.",
      ".##...@@@@...##.",
      ".##....@@....##.",
      ".##..........##.",
      ".##..........##.",
      "................",
    ],
  },
  "move-ins": {
    key: "move-ins",
    label: "Move-ins",
    meaning: "A unit filled: a box inside the open door",
    objects: "roll-up door frame + raised curtain + moving box",
    uses: "Move-in Reports, conversions, Ad → move-in tracking",
    group: "Leads",
    bitmap: [
      "................",
      ".##############.",
      ".##############.",
      ".##..........##.",
      ".##############.",
      ".##..........##.",
      ".##..........##.",
      ".##..........##.",
      ".##.@@@..@@@.##.",
      ".##.@@@..@@@.##.",
      ".##.@@@@@@@@.##.",
      ".##.@@@@@@@@.##.",
      ".##.@@@@@@@@.##.",
      ".##.@@@@@@@@.##.",
      ".##.@@@@@@@@.##.",
      "................",
    ],
  },
  "reserve": {
    key: "reserve",
    label: "Reserve",
    meaning: "A unit held for you: the key on its unit tag",
    objects: "unit key + paper key tag",
    uses: "Reserve on the page (storEDGE), reservations, booking",
    group: "Leads",
    bitmap: [
      ".@@@@@..........",
      ".@@@@@..........",
      ".@@..@..........",
      ".@@@@@..........",
      ".@@@@@..........",
      "...#............",
      "...#............",
      ".######.........",
      "##....##........",
      "##....##########",
      "##....##########",
      "##....##...##.##",
      ".######....##.##",
      "................",
      "................",
      "................",
    ],
  },
  "proven-ads": {
    key: "proven-ads",
    label: "Proven Ads",
    meaning: "An ad that already worked: a signboard with a check",
    objects: "roadside signboard on two posts + check",
    uses: "Studio › Proven Ads, Proven Ads cards, homepage",
    group: "Studio",
    bitmap: [
      "................",
      "################",
      "################",
      "##..........@@##",
      "##.........@@.##",
      "##..@@....@@..##",
      "##...@@..@@...##",
      "##....@@@@....##",
      "##.....@@.....##",
      "################",
      "################",
      "...##......##...",
      "...##......##...",
      "...##......##...",
      "...##......##...",
      "...##......##...",
    ],
  },
  "recreate": {
    key: "recreate",
    label: "Recreate",
    meaning: "Make your own from a proven ad: a sign and its copy",
    objects: "two signboards, one offset behind the other + one post",
    uses: "Recreate this ad, Duplicate, Save to library",
    group: "Studio",
    bitmap: [
      "................",
      ".....###########",
      ".....###########",
      ".....#.......###",
      "@@@@@@@@@@@..###",
      "@@@@@@@@@@@..###",
      "@@@@@@@@@@@..###",
      "@@@@@@@@@@@..###",
      "@@@@@@@@@@@..###",
      "@@@@@@@@@@@.....",
      "@@@@@@@@@@@.....",
      "....##..........",
      "....##..........",
      "....##..........",
      "....##..........",
      "....##..........",
    ],
  },
  "ad-studio": {
    key: "ad-studio",
    label: "Ad Studio",
    meaning: "Make an ad: a signboard and a marker",
    objects: "signboard + sign-painter's marker",
    uses: "Creative Studio, Ad Generator, Ad Studio",
    group: "Studio",
    bitmap: [
      "................",
      "###########.....",
      "###########.....",
      "###########.....",
      "###########..@..",
      "###########.@@@.",
      "###########@@@@@",
      "####.......@@@@.",
      "####......@@@@..",
      "####.....@@@@...",
      "####....@@@@....",
      "####...@@@@.....",
      "####...@@@......",
      ".##....@@.......",
      ".##.............",
      ".##.............",
    ],
  },
  "campaigns": {
    key: "campaigns",
    label: "Campaigns",
    meaning: "Ads going out: a signboard sending",
    objects: "signboard + outgoing arrow",
    uses: "Campaigns, Publisher, ads live, Meta/Google publishing",
    group: "Studio",
    bitmap: [
      "................",
      ".........@@@@@@.",
      ".........@@@@@@.",
      "............@@@.",
      "...........@@@@.",
      "..........@@@.@.",
      ".........@@@..@.",
      "##########@#....",
      "#########.......",
      "#########.......",
      "#########.......",
      "#########.......",
      "#########.......",
      "#########.......",
      "....##..........",
      "....##..........",
    ],
  },
  "landing-page": {
    key: "landing-page",
    label: "Landing page",
    meaning: "A page per ad: a browser page with a unit door on it",
    objects: "browser window + ribbed roll-up door",
    uses: "Landing Pages, ad pages, Reserve flow pages",
    group: "Studio",
    bitmap: [
      "################",
      "#.#.#.##########",
      "################",
      "#..............#",
      "#..............#",
      "#..............#",
      "#..@@@@@@@@@@..#",
      "#..@@@@@@@@@@..#",
      "#..............#",
      "#..@@@@@@@@@@..#",
      "#..@@@@@@@@@@..#",
      "#..............#",
      "#..@@@@@@@@@@..#",
      "#..@@@@@@@@@@..#",
      "#..@@@@@@@@@@..#",
      "################",
    ],
  },
  "reports": {
    key: "reports",
    label: "Reports",
    meaning: "The monthly record: a ledger with one reading",
    objects: "ledger sheet + pie reading with one wedge out",
    uses: "Reports, monthly report, Move-in Reports, Insights",
    group: "Intelligence",
    bitmap: [
      ".##############.",
      ".##############.",
      ".##..........##.",
      ".##...##.@...##.",
      ".##..###.@@..##.",
      ".##.####.@@@.##.",
      ".##.########.##.",
      ".##.########.##.",
      ".##..######..##.",
      ".##...####...##.",
      ".##..........##.",
      ".##.########.##.",
      ".##..........##.",
      ".##.######...##.",
      ".##..........##.",
      ".##############.",
    ],
  },
  "market": {
    key: "market",
    label: "Market",
    meaning: "Your trade area: a pin on its ground",
    objects: "map pin (solid, eyelet knocked out) + radius ring on the ground",
    uses: "Market intel, Your market mapped, audit map",
    group: "Intelligence",
    bitmap: [
      "......####......",
      ".....######.....",
      "....########....",
      "....###..###....",
      "....###..###....",
      "....########....",
      ".....######.....",
      "......####......",
      ".......@@.......",
      "....####@###....",
      "..##....@...##..",
      ".#......@.....#.",
      "..##........##..",
      "....########....",
      "................",
      "................",
    ],
  },
  "pricing": {
    key: "pricing",
    label: "Pricing",
    meaning: "What a unit costs: the rate tag",
    objects: "hang tag (rate tag) with eyelet",
    uses: "/pricing, unit rates, offers",
    group: "Intelligence",
    bitmap: [
      "................",
      "................",
      ".....##########.",
      "....###########.",
      "...############.",
      "..####.....####.",
      ".###.##########.",
      ".##..@#########.",
      ".##..@#########.",
      ".###.##########.",
      "..####.....####.",
      "...############.",
      "....###########.",
      ".....##########.",
      "................",
      "................",
    ],
  },
  "revenue": {
    key: "revenue",
    label: "Revenue",
    meaning: "Rates moving up: a rate tag with a rising arrow",
    objects: "rate tag + up arrow",
    uses: "Revenue intel, ECRI Finder, Cost per Move-in, ROI",
    group: "Intelligence",
    bitmap: [
      "................",
      "............@@..",
      "...........@@@@.",
      "..........@@@@@@",
      "............@@..",
      "............@@..",
      "....######..@@..",
      "...#######..@@..",
      "..########..@@..",
      ".##.######..@@..",
      ".##.######..@@..",
      "..########..@@..",
      "...#######..@@..",
      "....######..@@..",
      "................",
      "................",
    ],
  },
  "diagnostic": {
    key: "diagnostic",
    label: "Diagnostic",
    meaning: "A look inside: a lens over a unit door",
    objects: "inspector's lens + unit door",
    uses: "Free Diagnostic, audit tool, Diagnostics, search",
    group: "Intelligence",
    bitmap: [
      "...#####........",
      "..##...##.......",
      ".##.....##......",
      "##..###..##.....",
      "##..#.#..##.....",
      "##..#.#..##.....",
      "##..#.#..##.....",
      ".##.....##......",
      "..##...###......",
      "...#######@.....",
      ".........@@@....",
      "..........@@@...",
      "...........@@@..",
      "............@@@.",
      ".............@@.",
      "................",
    ],
  },
  "tools": {
    key: "tools",
    label: "Tools",
    meaning: "Owner calculators: a tape measure",
    objects: "tape measure case + pulled tape + hook",
    uses: "/tools calculators, ROI calculator, Calculator",
    group: "Intelligence",
    bitmap: [
      "................",
      "##########......",
      "##########......",
      "###....###......",
      "##..##..##......",
      "##.####.##......",
      "##.####.##......",
      "##..##..##......",
      "###....###......",
      "##########......",
      "##########@@@@@@",
      "##########@@@@@@",
      "...........#.#@@",
      "..............@@",
      "................",
      "................",
    ],
  },
  "access": {
    key: "access",
    label: "Access",
    meaning: "Sign in with your code: the gate keypad",
    objects: "gate keypad: screen + keys",
    uses: "Portal sign-in, access code, Sign up, login",
    group: "Account",
    bitmap: [
      "...##########...",
      "...##########...",
      "...##@@@@@@##...",
      "...##########...",
      "...##########...",
      "...#..#..#..##..",
      "...##########...",
      "...#..#..#..##..",
      "...##########...",
      "...##########...",
      "...##########...",
      ".......##.......",
      ".......##.......",
      ".......##.......",
      ".....######.....",
      "................",
    ],
  },
  "security": {
    key: "security",
    label: "Security",
    meaning: "Your data, locked: the unit padlock",
    objects: "padlock shackle + body + keyhole",
    uses: "Privacy, Terms, Data deletion, compliance, 2FA",
    group: "Account",
    bitmap: [
      "................",
      ".....######.....",
      "....########....",
      "....##....##....",
      "....##....##....",
      "....##....##....",
      "...##########...",
      "..############..",
      "..############..",
      "..######@#####..",
      "..#####@@@####..",
      "..######@#####..",
      "..######@#####..",
      "..############..",
      "..############..",
      "................",
    ],
  },
  "upload": {
    key: "upload",
    label: "Upload",
    meaning: "Bring your data in: a box with an arrow up",
    objects: "moving box + up arrow",
    uses: "Upload FMS reports, PMS data, PMS Queue, media upload",
    group: "Account",
    bitmap: [
      ".......@@.......",
      "......@@@@......",
      ".....@@@@@@.....",
      "....@@@@@@@@....",
      ".......@@.......",
      ".......@@.......",
      ".......@@.......",
      ".......@@.......",
      ".####..@@..####.",
      ".####......####.",
      ".##############.",
      ".##############.",
      ".##############.",
      ".##############.",
      ".##############.",
      "................",
    ],
  },
  "onboarding": {
    key: "onboarding",
    label: "Onboarding",
    meaning: "Getting set up: a box on a hand truck",
    objects: "hand truck (dolly) + moving box",
    uses: "Setup wizard, portal onboarding, Get started",
    group: "Account",
    bitmap: [
      "##..............",
      ".##.............",
      ".##.............",
      ".##.............",
      ".##..@@@@@@@@@..",
      ".##..@@@@.@@@@..",
      ".##..@@@@.@@@@..",
      ".##..@@@@@@@@@..",
      ".##..@@@@@@@@@..",
      ".##..@@@@@@@@@..",
      ".##..@@@@@@@@@..",
      ".##.............",
      ".##############.",
      "###############.",
      "###.............",
      ".#..............",
    ],
  },
  "calls": {
    key: "calls",
    label: "Calls",
    meaning: "Phone calls from ads: the office handset",
    objects: "office handset",
    uses: "Call tracking, Calls, Book a call, Talk to us",
    group: "Account",
    bitmap: [
      "................",
      ".###............",
      "####............",
      "####............",
      "###.............",
      "###.............",
      ".###............",
      "..###...........",
      "...###..........",
      "....####...##...",
      ".....#########..",
      "......########..",
      "........#####...",
      "................",
      "................",
      "................",
    ],
  },
  "messages": {
    key: "messages",
    label: "Messages",
    meaning: "A note to or from the office: a square speech card",
    objects: "office note card + speech tail",
    uses: "Messages, contact, client updates",
    group: "Account",
    bitmap: [
      "................",
      "################",
      "################",
      "###..........###",
      "################",
      "###.......######",
      "################",
      "################",
      "################",
      "#####...........",
      "####............",
      "###.............",
      "##..............",
      "................",
      "................",
      "................",
    ],
  },
  "settings": {
    key: "settings",
    label: "Settings",
    meaning: "Tune it: door slats set as sliders",
    objects: "roll-up door (header, jambs, slats) + slider knobs",
    uses: "Settings, preferences, controls",
    group: "Account",
    bitmap: [
      "################",
      "################",
      "#..............#",
      "#..###.........#",
      "################",
      "#..###.........#",
      "#..............#",
      "#.........###..#",
      "################",
      "#.........###..#",
      "#..............#",
      "#.....###......#",
      "################",
      "#.....###......#",
      "#..............#",
      "#..............#",
    ],
  },
  "help": {
    key: "help",
    label: "Help",
    meaning: "Questions answered: the hanging office sign",
    objects: "projecting office sign on a wall bracket + question mark",
    uses: "FAQ, Help, Docs, Guide",
    group: "Account",
    bitmap: [
      "#...............",
      "###############.",
      "#..#.......#....",
      "...#.......#....",
      ".##############.",
      ".##############.",
      ".#####....#####.",
      ".####..##..####.",
      ".#########.####.",
      ".#######..#####.",
      ".######..######.",
      ".##############.",
      ".######..######.",
      ".##############.",
      ".##############.",
      "................",
    ],
  },
  "links": {
    key: "links",
    label: "Links",
    meaning: "Where a click came from: two links of a gate chain",
    objects: "gate chain, two links",
    uses: "Tracking links (portal index)",
    group: "Added",
    bitmap: [
      "................",
      "................",
      "................",
      "..######........",
      ".########.......",
      "##......##......",
      "##....@@@@@@@@..",
      "##...@@.##..@@@.",
      "##...@@.##...@@.",
      ".#######.....@@.",
      "..#####@@...@@@.",
      ".......@@@@@@@@.",
      "........@@@@@@..",
      "................",
      "................",
      "................",
    ],
  },
  "posts": {
    key: "posts",
    label: "Posts",
    meaning: "A notice pinned up: a card on the office board",
    objects: "office notice card + push pin",
    uses: "Google Business and social posts (portal index)",
    group: "Added",
    bitmap: [
      ".......@@.......",
      "......@@@@......",
      ".......@@.......",
      ".##############.",
      ".##############.",
      ".###........###.",
      ".##############.",
      ".###.....######.",
      ".##############.",
      ".###.......####.",
      ".##############.",
      ".##############.",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  "reviews": {
    key: "reviews",
    label: "Reviews",
    meaning: "What renters say: a comment card with a star",
    objects: "comment card + speech tail + star",
    uses: "Google reviews (portal index, Reviews)",
    group: "Added",
    bitmap: [
      "................",
      "################",
      "################",
      "##............##",
      "##.....@......##",
      "##....@@@.....##",
      "##.@@@@@@@@@..##",
      "##..@@@@@@@...##",
      "##...@@.@@....##",
      "##..@@...@@...##",
      "##............##",
      "################",
      "################",
      "...........#####",
      "............####",
      ".............###",
    ],
  },
};

/** Facility unit-type primitives (10×10), keyed like the repo's UNIT_TYPES plus "tower". */
export type FacilityType = "drive_up" | "climate_controlled" | "vehicle" | "business" | "general" | "tower";

export const FACILITY_TYPES: Record<FacilityType, { label: string; bitmap: string[] }> = {
  "drive_up": {
    label: "Drive-up",
    bitmap: [
      "##########",
      "#........#",
      "#.######.#",
      "#.######.#",
      "#........#",
      "#.######.#",
      "#.######.#",
      "#........#",
      "#.######.#",
      "##########",
    ],
  },
  "climate_controlled": {
    label: "Climate",
    bitmap: [
      "....##....",
      "...#..#...",
      "...#..#.##",
      "...#..#...",
      "...####.##",
      "...####...",
      "..######..",
      "..######..",
      "..######..",
      "...####...",
    ],
  },
  "vehicle": {
    label: "Vehicle · RV · boat",
    bitmap: [
      ".....#....",
      ".....##...",
      ".....###..",
      ".....####.",
      ".....#####",
      ".....#....",
      "##########",
      ".########.",
      "..######..",
      "..........",
    ],
  },
  "business": {
    label: "Business",
    bitmap: [
      "...####...",
      "...####...",
      "...####...",
      "..........",
      "####..####",
      "####..####",
      "####..####",
      "####..####",
      "..........",
      "##########",
    ],
  },
  "general": {
    label: "General",
    bitmap: [
      "####..####",
      "####..####",
      "####..####",
      "####..####",
      "..........",
      "..........",
      "####..####",
      "####..####",
      "####..####",
      "####..####",
    ],
  },
  "tower": {
    label: "Urban tower",
    bitmap: [
      "..######..",
      "..#....#..",
      "..######..",
      "..#....#..",
      "..######..",
      "..#....#..",
      "..######..",
      "..#....#..",
      "..######..",
      "##########",
    ],
  },
};
