"use client";

import Cite from "@/components/marketing/cite";
import { CountUp } from "@/components/motion/count-up";
import { Reveal, RevealStagger, RevealItem } from "@/components/motion/reveal";

/**
 * § 00 · NUMBERS — the industry/forecast strip. Cited industry figures
 * plus the three year-one goals, clearly labeled FORECAST (no fake
 * "live" framing; the synthetic monitor triptych was retired).
 */
const CELLS: Array<{
  context: string;
  label: string;
  value: React.ReactNode;
  caption: string;
  cites?: number[];
}> = [
  {
    context: "Industry · 2025",
    label: "U.S. storage asset class",
    value: <CountUp to={432} prefix="$" suffix="B" />,
    caption:
      "Total value of U.S. self-storage real estate. NOI growth has beat inflation by 190 basis points a year since 2008.",
    cites: [4, 9],
  },
  {
    context: "Industry · 2025",
    label: "Occupancy gap",
    value: <CountUp to={5} suffix=" pts" />,
    caption:
      "REITs run 92.6% same-store occupancy. Independents average 87.2%. The space between is the lever, and it closes with marketing, not location.",
    cites: [1, 2],
  },
  {
    context: "Industry · Benchmark",
    label: "Revenue in the building",
    value: <CountUp to={72} prefix="$" suffix="k" />,
    caption:
      "What a 500-unit facility leaves in the building at the typical occupancy gap, $120 a unit. Roughly $1.3M in asset value at a 5.5% cap.",
    cites: [3],
  },
  {
    context: "Forecast · Year 1",
    label: "Ad spend goal",
    value: <CountUp to={10} prefix="$" suffix="M" />,
    caption:
      "ad spend StorageAds will put to work by EOY. Every dollar buying move-ins, not sitting in a vendor's queue.",
  },
  {
    context: "Forecast · Year 1",
    label: "Facilities goal",
    value: <CountUp to={250} />,
    caption: "operators live on the system by EOY. Partner operators carry the growth.",
  },
  {
    context: "Forecast · Year 1",
    label: "Move-ins generated",
    value: <CountUp to={10} suffix="k" />,
    caption:
      "signed leases generated by StorageAds campaigns. Operators pay for outcomes, not vendor reports.",
  },
];

export default function NumbersStrip() {
  return (
    <section aria-label="Industry and forecast numbers">
      <div className="max-w-[1380px] mx-auto px-4 sm:px-6 lg:px-10 pb-14 sm:pb-20">
        <Reveal>
          <div
            className="flex items-center justify-between gap-3"
            style={{ borderBottom: "1px solid var(--line)", paddingBottom: 10 }}
          >
            <span
              style={{
                fontFamily: "var(--mono)",
                fontSize: 10,
                letterSpacing: "var(--track-label)",
                textTransform: "uppercase",
                fontWeight: 600,
                color: "var(--accent)",
              }}
            >
              § 00 · Numbers
            </span>
            <span
              className="hidden sm:block"
              style={{
                fontFamily: "var(--mono)",
                fontSize: 10,
                letterSpacing: "var(--track-label)",
                textTransform: "uppercase",
                color: "var(--text-faint)",
              }}
            >
              n = 6 · industry · forecast
            </span>
          </div>
        </Reveal>

        <RevealStagger stagger={0.05} className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3">
          {CELLS.map((cell, i) => (
            <RevealItem
              key={cell.label}
              className="py-6 sm:p-6"
              style={{
                borderBottom: "1px solid var(--line-dim)",
                borderRight: "1px solid var(--line-dim)",
              }}
            >
              <p
                style={{
                  fontFamily: "var(--mono)",
                  fontSize: 9,
                  letterSpacing: "0.12em",
                  textTransform: "uppercase",
                  color: cell.context.startsWith("Forecast")
                    ? "var(--hue-c)"
                    : "var(--text-faint)",
                  marginBottom: 10,
                }}
              >
                #{String(i + 1).padStart(2, "0")} · {cell.context}
              </p>
              <p
                style={{
                  fontFamily: "var(--serif)",
                  fontWeight: 800,
                  fontSize: "var(--type-num)",
                  letterSpacing: "var(--track-tighter)",
                  lineHeight: 1,
                  color: "var(--text-accent)",
                  fontVariantNumeric: "tabular-nums",
                }}
              >
                {cell.value}
              </p>
              <p style={{ fontSize: 13, fontWeight: 600, color: "var(--text)", marginTop: 8 }}>
                {cell.label}
                {cell.cites && <Cite n={cell.cites} />}
              </p>
              <p style={{ fontSize: 12, lineHeight: 1.55, color: "var(--text-faint)", marginTop: 4 }}>
                {cell.caption}
              </p>
            </RevealItem>
          ))}
        </RevealStagger>
      </div>
    </section>
  );
}
